language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+

  before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - "./gradlew clean build -PdisablePreDex --stacktrace"

deploy:
  provider: testfairy
  api-key: "02273d28cdd18638d5f7cebe52460b6c67143c9f"
  app-file: Application\build\outputs\apk\Application-debug.apk
  keystore-file: debug.keystore
  storepass: android
  alias: android
